apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-frbo
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-frbo@sha256:327b81575cdf0c86ae4cf360c2af0964d3334030f56ea09d27709c98a9b2d85c
        name: my-python
        resources: {}
status: {}
