apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ewru
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-ewru@sha256:6ee2f9758c322b85882d6eb2ca456806bc472c58cca828f89818f71f4415a6cb
        name: my-nodejs
        resources: {}
status: {}
